// constants/ocorrencias.js

// Regiões organizadas em ordem alfabética
export const REGIOES = [
  { label: 'Agreste', value: 'Agreste' },
  { label: 'RMR', value: 'RMR' },
  { label: 'Sertão', value: 'Sertão' },
  { label: 'Zona da mata', value: 'Zona da mata' },
];

export const GRUPAMENTOS = [
  { label: 'GBAPH', value: 'GBAPH' },
  { label: 'GBI', value: 'GBI' },
  { label: 'GBMar', value: 'GBMar' },
  { label: 'GBS', value: 'GBS' },
];

export const NATUREZAS = [
  { label: 'APH', value: 'APH' },
  { label: 'Incêndio', value: 'Incêndio' },
  { label: 'Prevenção', value: 'Prevenção' },
  { label: 'Produtos perigosos', value: 'Produtos perigosos' },
  { label: 'Salvamento', value: 'Resgate' },
];

// Grupos de ocorrência organizados alfabeticamente
export const GRUPOS_OCORRENCIA = [
  { label: "Acidente de Trânsito Atropelamento", value: "Acidente de Trânsito Atropelamento" },
  { label: "Acidente de Trânsito Choque", value: "Acidente de Trânsito Choque" },
  { label: "Acidente de Trânsito Colisão Abalroamento", value: "Acidente de Trânsito Colisão Abalroamento" },
  { label: "Apoio em Operações", value: "Apoio em Operações" },
  { label: "APH Diversos", value: "APH Diversos" },
  { label: "Emergência Cardíaca", value: "Emergência Cardíaca" },
  { label: "Emergência Respiratória", value: "Emergência Respiratória" },
  { label: "Emergências Clínicas Diversas", value: "Emergências Clínicas Diversas" },
  { label: "Evento com Animal", value: "Evento com Animal" },
  { label: "Evento com Árvores", value: "Evento com Árvores" },
  { label: "Evento com Cadáver", value: "Evento com Cadáver" },
  { label: "Evento com Meio de Transporte", value: "Evento com Meio de Transporte" },
  { label: "Evento com Pessoa", value: "Evento com Pessoa" },
  { label: "Evento Esportivo", value: "Evento Esportivo" },
  { label: "Evento Festivo", value: "Evento Festivo" },
  { label: "Explosão", value: "Explosão" },
  { label: "Incêndio em Edificação Concentração de Público", value: "Incêndio em Edificação Concentração de Público" },
  { label: "Incêndio em Edificação Escolar", value: "Incêndio em Edificação Escolar" },
  { label: "Incêndio em Edificação Industrial", value: "Incêndio em Edificação Industrial" },
  { label: "Incêndio em Edificação Outros", value: "Incêndio em Edificação Outros" },
  { label: "Incêndio em Edificação Residencial", value: "Incêndio em Edificação Residencial" },
  { label: "Incêndio em Meio de Transporte Terrestre", value: "Incêndio em Meio de Transporte Terrestre" },
  { label: "Incêndio em Vegetação", value: "Incêndio em Vegetação" },
  { label: "Incêndio em Via Pública", value: "Incêndio em Via Pública" },
  { label: "Incêndios Diversos", value: "Incêndios Diversos" },
  { label: "Prevenção Aquática", value: "Prevenção Aquática" },
  { label: "Prevenção Diversos", value: "Prevenção Diversos" },
  { label: "Queda", value: "Queda" },
  { label: "Vazamento", value: "Vazamento" },
  { label: "Vítima de Agressão", value: "Vítima de Agressão" }
].sort((a, b) => a.label.localeCompare(b.label));

export const SUBGRUPOS_OCORRENCIA = [
  { label: 'Afogamento', value: 'Afogamento' },
  { label: 'Agência Bancária', value: 'Agência Bancária' },
  { label: 'Arma Branca', value: 'Arma Branca' },
  { label: 'Auto Passeio', value: 'Auto Passeio' },
  { label: 'Auto Passeio x Auto Passeio', value: 'Auto Passeio x Auto Passeio' },
  { label: 'Auto Passeio x Bicicleta', value: 'Auto Passeio x Bicicleta' },
  { label: 'Auto Passeio x Motocicleta', value: 'Auto Passeio x Motocicleta' },
  { label: 'Auto Passeio x Ônibus ou Micro-Ônibus', value: 'Auto Passeio x Ônibus ou Micro-Ônibus' },
  { label: 'Auto Passeio x Van ou Similar', value: 'Auto Passeio x Van ou Similar' },
  { label: 'Bar/Lanchonete ou Similar', value: 'Bar/Lanchonete ou Similar' },
  { label: 'Barbearia/Salão de Beleza ou Similar', value: 'Barbearia/Salão de Beleza ou Similar' },
  { label: 'Bicicleta', value: 'Bicicleta' },
  { label: 'Caminhão', value: 'Caminhão' },
  { label: 'Canino Cão', value: 'Canino Cão' },
  { label: 'Convulsão', value: 'Convulsão' },
  { label: 'Crise Hipertensiva', value: 'Crise Hipertensiva' },
  { label: 'Deslizamento/Escorregamento', value: 'Deslizamento/Escorregamento' },
  { label: 'Desmaio /Síncope', value: 'Desmaio /Síncope' },
  { label: 'Diversos', value: 'Diversos' },
  { label: 'Distúrbio Mental com Risco', value: 'Distúrbio Mental com Risco' },
  { label: 'Ensino Superior', value: 'Ensino Superior' },
  { label: 'Equino', value: 'Equino' },
  { label: 'Fábrica ou Revenda de Artefato Explosivo', value: 'Fábrica ou Revenda de Artefato Explosivo' },
  { label: 'Fábrica ou Revenda de Fogos de Artifício', value: 'Fábrica ou Revenda de Fogos de Artifício' },
  { label: 'Felino Gato', value: 'Felino Gato' },
  { label: 'Fiação Elétrica de Poste', value: 'Fiação Elétrica de Poste' },
  { label: 'Física', value: 'Física' },
  { label: 'Fogo', value: 'Fogo' },
  { label: 'Gravidez', value: 'Gravidez' },
  { label: 'Igreja/Templo ou Similar', value: 'Igreja/Templo ou Similar' },
  { label: 'Inseto Abelha', value: 'Inseto Abelha' },
  { label: 'Inseto Maribondo', value: 'Inseto Maribondo' },
  { label: 'Inseto Outro', value: 'Inseto Outro' },
  { label: 'Intoxicação Endógena', value: 'Intoxicação Endógena' },
  { label: 'Local Especial para Tratamento e Reciclagem', value: 'Local Especial para Tratamento e Reciclagem' },
  { label: 'Mangue', value: 'Mangue' },
  { label: 'Mato', value: 'Mato' },
  { label: 'Máquina Agrícola', value: 'Máquina Agrícola' },
  { label: 'Mercado', value: 'Mercado' },
  { label: 'Moto', value: 'Moto' },
  { label: 'Motocicleta', value: 'Motocicleta' },
  { label: 'Motocicleta x Motocicleta', value: 'Motocicleta x Motocicleta' },
  { label: 'Motocicleta x Ônibus ou Micro-Ônibus', value: 'Motocicleta x Ônibus ou Micro-Ônibus' },
  { label: 'Motocicleta x Veículo de Carga Não Perigosa', value: 'Motocicleta x Veículo de Carga Não Perigosa' },
  { label: 'Multifamiliar Casas Conjugadas', value: 'Multifamiliar Casas Conjugadas' },
  { label: 'Multifamiliar Edificação Elevada', value: 'Multifamiliar Edificação Elevada' },
  { label: 'Oficina', value: 'Oficina' },
  { label: 'Ônibus ou Micro-Ônibus', value: 'Ônibus ou Micro-Ônibus' },
  { label: 'Outro', value: 'Outro' },
  { label: 'Pessoa em Local de Difícil Acesso (Trilha/Montanha/Caverna)', value: 'Pessoa em Local de Difícil Acesso (Trilha/Montanha/Caverna)' },
  { label: 'Pessoa Ilhada', value: 'Pessoa Ilhada' },
  { label: 'Preso em Elevador', value: 'Preso em Elevador' },
  { label: 'Preso em Ferragem de Veículo', value: 'Preso em Ferragem de Veículo' },
  { label: 'Problemas Cardíacos', value: 'Problemas Cardíacos' },
  { label: 'Protesto', value: 'Protesto' },
  { label: 'Queda da Própria Altura', value: 'Queda da Própria Altura' },
  { label: 'Queda de Árvore sobre Imóveis', value: 'Queda de Árvore sobre Imóveis' },
  { label: 'Queda de Bicicleta', value: 'Queda de Bicicleta' },
  { label: 'Queda de Moto', value: 'Queda de Moto' },
  { label: 'Queda de Nível Abaixo de 2M', value: 'Queda de Nível Abaixo de 2M' },
  { label: 'Queda de Nível Acima de 2M', value: 'Queda de Nível Acima de 2M' },
  { label: 'Resgate Aquático', value: 'Resgate Aquático' },
  { label: 'Silvestre Cobra', value: 'Silvestre Cobra' },
  { label: 'Silvestre Jacaré', value: 'Silvestre Jacaré' },
  { label: 'Silvestre Onça', value: 'Silvestre Onça' },
  { label: 'Silvestre Outro', value: 'Silvestre Outro' },
  { label: 'Supermercado', value: 'Supermercado' },
  { label: 'Tentativa de Suicídio', value: 'Tentativa de Suicídio' },
  { label: 'Têxtil', value: 'Têxtil' },
  { label: 'Unifamiliar Casa Residência', value: 'Unifamiliar Casa Residência' },
  { label: 'Van ou Similar', value: 'Van ou Similar' }
];



export const SITUACOES = [
  { label: 'Atendida', value: 'Atendida' },
  { label: 'Não Atendida', value: 'Não Atendida' },
  { label: 'Sem Atuação', value: 'Sem Atuação' },
  { label: 'Cancelada', value: 'Cancelada' },
];

export const SEXOS = [
  { label: 'Feminino', value: 'Feminino' },
  { label: 'Masculino', value: 'Masculino' },
  { label: 'Outro', value: 'Outro' },
];

export const CLASSIFICACOES = [
  { label: 'Ferida grave', value: 'Ferida grave' },
  { label: 'Ferida leve', value: 'Ferida leve' },
  { label: 'Óbito', value: 'Óbito' },
  { label: 'Vítima ilesa', value: 'Vítima ilesa' },
];

export const DESTINOS = [
  { label: 'Encaminhado ao Suporte Avançado', value: 'Encaminhado ao Suporte Avançado' },
  { label: 'Encaminhado ao Suporte Básico', value: 'Encaminhado ao Suporte Básico' },
  { label: 'Entregue ao Hospital', value: 'Entregue ao Hospital' },
  { label: 'Óbito', value: 'Óbito' },
  { label: 'Outro', value: 'Outro' },
  { label: 'Permaneceu no Local após atendimento', value: 'Permaneceu no Local após atendimento' },
];

export const ACIONAMENTOS = [
  { label: 'CIODS', value: 'CIODS' },
  { label: 'CO do Grupamento', value: 'CO do grupamento' },
  { label: 'Outro', value: 'Outro' },
  { label: 'Pessoalmente', value: 'Pessoalmente' },
];

export const MUNICIPIOS_PERNAMBUCO = [
  { "label": "Abreu e Lima", "value": "Abreu e Lima" },
  { "label": "Afogados da Ingazeira", "value": "Afogados da Ingazeira" },
  { "label": "Afrânio", "value": "Afrânio" },
  { "label": "Agrestina", "value": "Agrestina" },
  { "label": "Água Preta", "value": "Água Preta" },
  { "label": "Águas Belas", "value": "Águas Belas" },
  { "label": "Alagoinha", "value": "Alagoinha" },
  { "label": "Aliança", "value": "Aliança" },
  { "label": "Altinho", "value": "Altinho" },
  { "label": "Amaraji", "value": "Amaraji" },
  { "label": "Angelim", "value": "Angelim" },
  { "label": "Araçoiaba", "value": "Araçoiaba" },
  { "label": "Araripina", "value": "Araripina" },
  { "label": "Arcoverde", "value": "Arcoverde" },
  { "label": "Barra de Guabiraba", "value": "Barra de Guabiraba" },
  { "label": "Barreiros", "value": "Barreiros" },
  { "label": "Belém de Maria", "value": "Belém de Maria" },
  { "label": "Belém do São Francisco", "value": "Belém do São Francisco" },
  { "label": "Belo Jardim", "value": "Belo Jardim" },
  { "label": "Betânia", "value": "Betânia" },
  { "label": "Bezerros", "value": "Bezerros" },
  { "label": "Bodocó", "value": "Bodocó" },
  { "label": "Bom Conselho", "value": "Bom Conselho" },
  { "label": "Bom Jardim", "value": "Bom Jardim" },
  { "label": "Bonito", "value": "Bonito" },
  { "label": "Brejão", "value": "Brejão" },
  { "label": "Brejinho", "value": "Brejinho" },
  { "label": "Brejo da Madre de Deus", "value": "Brejo da Madre de Deus" },
  { "label": "Buenos Aires", "value": "Buenos Aires" },
  { "label": "Buíque", "value": "Buíque" },
  { "label": "Cabo de Santo Agostinho", "value": "Cabo de Santo Agostinho" },
  { "label": "Cabrobó", "value": "Cabrobó" },
  { "label": "Cachoeirinha", "value": "Cachoeirinha" },
  { "label": "Caetés", "value": "Caetés" },
  { "label": "Calçado", "value": "Calçado" },
  { "label": "Calumbi", "value": "Calumbi" },
  { "label": "Camaragibe", "value": "Camaragibe" },
  { "label": "Camocim de São Félix", "value": "Camocim de São Félix" },
  { "label": "Camutanga", "value": "Camutanga" },
  { "label": "Canhotinho", "value": "Canhotinho" },
  { "label": "Capoeiras", "value": "Capoeiras" },
  { "label": "Carnaíba", "value": "Carnaíba" },
  { "label": "Carnaubeira da Penha", "value": "Carnaubeira da Penha" },
  { "label": "Carpina", "value": "Carpina" },
  { "label": "Caruaru", "value": "Caruaru" },
  { "label": "Casinhas", "value": "Casinhas" },
  { "label": "Catende", "value": "Catende" },
  { "label": "Cedro", "value": "Cedro" },
  { "label": "Chã de Alegria", "value": "Chã de Alegria" },
  { "label": "Chã Grande", "value": "Chã Grande" },
  { "label": "Condado", "value": "Condado" },
  { "label": "Correntes", "value": "Correntes" },
  { "label": "Cortês", "value": "Cortês" },
  { "label": "Cumaru", "value": "Cumaru" },
  { "label": "Cupira", "value": "Cupira" },
  { "label": "Custódia", "value": "Custódia" },
  { "label": "Dormentes", "value": "Dormentes" },
  { "label": "Escada", "value": "Escada" },
  { "label": "Exu", "value": "Exu" },
  { "label": "Feira Nova", "value": "Feira Nova" },
  { "label": "Ferreiros", "value": "Ferreiros" },
  { "label": "Flores", "value": "Flores" },
  { "label": "Floresta", "value": "Floresta" },
  { "label": "Frei Miguelinho", "value": "Frei Miguelinho" },
  { "label": "Gameleira", "value": "Gameleira" },
  { "label": "Garanhuns", "value": "Garanhuns" },
  { "label": "Glória do Goitá", "value": "Glória do Goitá" },
  { "label": "Goiana", "value": "Goiana" },
  { "label": "Granito", "value": "Granito" },
  { "label": "Gravatá", "value": "Gravatá" },
  { "label": "Iati", "value": "Iati" },
  { "label": "Ibimirim", "value": "Ibimirim" },
  { "label": "Ibirajuba", "value": "Ibirajuba" },
  { "label": "Igarassu", "value": "Igarassu" },
  { "label": "Iguaracy", "value": "Iguaracy" },
  { "label": "Inajá", "value": "Inajá" },
  { "label": "Ingazeira", "value": "Ingazeira" },
  { "label": "Ipojuca", "value": "Ipojuca" },
  { "label": "Ipubi", "value": "Ipubi" },
  { "label": "Itacuruba", "value": "Itacuruba" },
  { "label": "Itaíba", "value": "Itaíba" },
  { "label": "Ilha de Itamaracá", "value": "Ilha de Itamaracá" },
  { "label": "Itambé", "value": "Itambé" },
  { "label": "Itapetim", "value": "Itapetim" },
  { "label": "Itapissuma", "value": "Itapissuma" },
  { "label": "Itaquitinga", "value": "Itaquitinga" },
  { "label": "Jaboatão dos Guararapes", "value": "Jaboatão dos Guararapes" },
  { "label": "Jaqueira", "value": "Jaqueira" },
  { "label": "Jataúba", "value": "Jataúba" },
  { "label": "Jatobá", "value": "Jatobá" },
  { "label": "João Alfredo", "value": "João Alfredo" },
  { "label": "Joaquim Nabuco", "value": "Joaquim Nabuco" },
  { "label": "Jucati", "value": "Jucati" },
  { "label": "Jupi", "value": "Jupi" },
  { "label": "Jurema", "value": "Jurema" },
  { "label": "Lagoa do Carro", "value": "Lagoa do Carro" },
  { "label": "Lagoa de Itaenga", "value": "Lagoa de Itaenga" },
  { "label": "Lagoa do Ouro", "value": "Lagoa do Ouro" },
  { "label": "Lagoa dos Gatos", "value": "Lagoa dos Gatos" },
  { "label": "Lagoa Grande", "value": "Lagoa Grande" },
  { "label": "Lajedo", "value": "Lajedo" },
  { "label": "Limoeiro", "value": "Limoeiro" },
  { "label": "Macaparana", "value": "Macaparana" },
  { "label": "Machados", "value": "Machados" },
  { "label": "Manari", "value": "Manari" },
  { "label": "Maraial", "value": "Maraial" },
  { "label": "Mirandiba", "value": "Mirandiba" },
  { "label": "Moreilândia", "value": "Moreilândia" },
  { "label": "Moreno", "value": "Moreno" },
  { "label": "Nazaré da Mata", "value": "Nazaré da Mata" },
  { "label": "Olinda", "value": "Olinda" },
  { "label": "Orobó", "value": "Orobó" },
  { "label": "Orocó", "value": "Orocó" },
  { "label": "Ouricuri", "value": "Ouricuri" },
  { "label": "Palmares", "value": "Palmares" },
  { "label": "Palmeirina", "value": "Palmeirina" },
  { "label": "Panelas", "value": "Panelas" },
  { "label": "Paranatama", "value": "Paranatama" },
  { "label": "Parnamirim", "value": "Parnamirim" },
  { "label": "Passira", "value": "Passira" },
  { "label": "Paudalho", "value": "Paudalho" },
  { "label": "Paulista", "value": "Paulista" },
  { "label": "Pedra", "value": "Pedra" },
  { "label": "Pesqueira", "value": "Pesqueira" },
  { "label": "Petrolândia", "value": "Petrolândia" },
  { "label": "Petrolina", "value": "Petrolina" },
  { "label": "Poção", "value": "Poção" },
  { "label": "Pombos", "value": "Pombos" },
  { "label": "Primavera", "value": "Primavera" },
  { "label": "Quipapá", "value": "Quipapá" },
  { "label": "Quixaba", "value": "Quixaba" },
  { "label": "Recife", "value": "Recife" },
  { "label": "Riacho das Almas", "value": "Riacho das Almas" },
  { "label": "Ribeirão", "value": "Ribeirão" },
  { "label": "Rio Formoso", "value": "Rio Formoso" },
  { "label": "Sairé", "value": "Sairé" },
  { "label": "Salgadinho", "value": "Salgadinho" },
  { "label": "Salgueiro", "value": "Salgueiro" },
  { "label": "Saloá", "value": "Saloá" },
  { "label": "Sanharó", "value": "Sanharó" },
  { "label": "Santa Cruz", "value": "Santa Cruz" },
  { "label": "Santa Cruz da Baixa Verde", "value": "Santa Cruz da Baixa Verde" },
  { "label": "Santa Cruz do Capibaribe", "value": "Santa Cruz do Capibaribe" },
  { "label": "Santa Filomena", "value": "Santa Filomena" },
  { "label": "Santa Maria da Boa Vista", "value": "Santa Maria da Boa Vista" },
  { "label": "Santa Maria do Cambucá", "value": "Santa Maria do Cambucá" },
  { "label": "Santa Terezinha", "value": "Santa Terezinha" },
  { "label": "São Benedito do Sul", "value": "São Benedito do Sul" },
  { "label": "São Bento do Una", "value": "São Bento do Una" },
  { "label": "São Caetano", "value": "São Caetano" },
  { "label": "São João", "value": "São João" },
  { "label": "São Joaquim do Monte", "value": "São Joaquim do Monte" },
  { "label": "São José da Coroa Grande", "value": "São José da Coroa Grande" },
  { "label": "São José do Belmonte", "value": "São José do Belmonte" },
  { "label": "São José do Egito", "value": "São José do Egito" },
  { "label": "São Lourenço da Mata", "value": "São Lourenço da Mata" },
  { "label": "São Vicente Férrer", "value": "São Vicente Férrer" },
  { "label": "Serra Talhada", "value": "Serra Talhada" },
  { "label": "Serrita", "value": "Serrita" },
  { "label": "Sertânia", "value": "Sertânia" },
  { "label": "Sirinhaém", "value": "Sirinhaém" },
  { "label": "Solidão", "value": "Solidão" },
  { "label": "Surubim", "value": "Surubim" },
  { "label": "Tabira", "value": "Tabira" },
  { "label": "Tacaimbó", "value": "Tacaimbó" },
  { "label": "Tacaratu", "value": "Tacaratu" },
  { "label": "Tamandaré", "value": "Tamandaré" },
  { "label": "Taquaritinga do Norte", "value": "Taquaritinga do Norte" },
  { "label": "Terezinha", "value": "Terezinha" },
  { "label": "Terra Nova", "value": "Terra Nova" },
  { "label": "Timbaúba", "value": "Timbaúba" },
  { "label": "Toritama", "value": "Toritama" },
  { "label": "Tracunhaém", "value": "Tracunhaém" },
  { "label": "Trindade", "value": "Trindade" },
  { "label": "Triunfo", "value": "Triunfo" },
  { "label": "Tupanatinga", "value": "Tupanatinga" },
  { "label": "Tuparetama", "value": "Tuparetama" },
  { "label": "Venturosa", "value": "Venturosa" },
  { "label": "Verdejante", "value": "Verdejante" },
  { "label": "Vertente do Lério", "value": "Vertente do Lério" },
  { "label": "Vertentes", "value": "Vertentes" },
  { "label": "Vicência", "value": "Vicência" },
  { "label": "Vitória de Santo Antão", "value": "Vitória de Santo Antão" },
  { "label": "Xexéu", "value": "Xexéu" }
];

export const TIPOS_LOGRADOURO = [
  { label: 'Alameda', value: 'Alameda' },
  { label: 'Avenida', value: 'Avenida' },
  { label: 'Estrada', value: 'Estrada' },
  { label: 'Rua', value: 'Rua' },
  { label: 'Travessa', value: 'Travessa' },
];


// Export padrão
export default GRUPOS_OCORRENCIA;
